### ISSUE TITLE
Default value for mosaic button

### ISSUE THREAD

**Issue by jgrygierek** [kunicmarko20/SonataAutoConfigureBundle#22]
Hi, I think that default value for mosaic button should be taken from `sonata_admin.show_mosaic_button` option. Currently it is set to true and I have to change it in each admin class.

**Comment by kunicmarko20** [comment]
Hi @jgrygierek, you are correct. I am away until Wednesday, would you be able to provide a PR? or maybe @gremo . I am able to merge it over my phone.

**Comment by gremo** [comment]
Mosaic button can be globally enable/disable for all admins (SonataAdminBundle configuration). Once you disable for all admin, you need to disable it for each admin... using the annotation, because default value is `true`.

As I said in a previous issue, in the `AdminOptions.php` class, all boolean variables should be NULL by default. This way, not providing defaults, will solve the issue.

This should be fixed in 1.x

**Comment by kunicmarko20** [comment]
And I thought that was the issue since the default value is `true`. I guess it is time to remove default values, @gremo are you able to do it?

**Comment by gremo** [comment]
Yes, but this would be a BC break, so... maybe 1.0?

**Comment by kunicmarko20** [comment]
0.x allows BC Breaks, and it's not a big change, so let's just add it, we did it already with a different config.

**Comment by OskarStark** [comment]
But you should ofc mention it somewhere
